### ISSUE TITLE
 US1 : En tant que visiteur, je veux consulter une épigraphe

### ISSUE THREAD

**Issue by Theo-Hafsaoui** [MasterDID2022/projet-s2#1]
## Description :
Afin de commencer le développement de notre logicielle, nous devons permettre la consultation
d'une épigraphie récupérée sur [epicherchel](http://ccj-epicherchel.huma-num.fr/interface/fiche.php?id=42)

#### diag. de sequence
```mermaid
sequenceDiagram
    visiteur->>front: veut voir l'epigraphie d'ID X
    front->>back: demande l'epigraphie d'ID X
    back->>web: demande l'epigraphie d'ID X
    web->>back: retourn l'epigraphie d'ID X en XML
    back->>back: traduit XML en instance d'epigraphie
    back->>front: retourne epigraphie
    front->>visiteur: affiche l'epigraphie
```
#### diag. de classe
```mermaid
---
title: Frontend pour US1
---
classDiagram

    note for Controller "utilise le Parser pour convertir\n la réponse JSON en object Epigraphie"

    class Vue {

    }

    class Controller {
        afficherEpigraphie(Json response)
    }

    class ApiFront {
        sendRequest(int id)
        receiveResponse(Json response)
    }

    class Parser {
        convertToEpigraphie(Json obj)
    }

    Vue <--> Controller
    Controller <-- Parser
    ApiFront <--> Controller
```
```mermaid
---
title: Backend pour US1
---
classDiagram

    class Epigraphie {

    }

    class SI {
        static String getFirstUrlOf(String XMLepigraphie)
    }

    class ApiBack {
        sendResponse(Json repons)
        receiveRequest(int id)
    }

    class DAO {
        PersiteEpigraphie(Epigraphie)
    }

    DAO <-- Epigraphie
    DAO <-- SI
    ApiBack<--> SI
```
### Exigences :
- [x] L'app possède une UI pour afficher l'epigraphie #2 
- [x] L'app peut récupérer une épigraphie de epicherchel #9 
- [x] L'app as une API *restfull* pour se connecter à sa BD #3 
- [x] L'app as une DAO avec *JPA* pour persister l'epigraphie #4 
- [x]  L'app est compilable avec maven, et ceux aussi sur GitHub (CI) #6
